### ISSUE TITLE
Please license your code

### ISSUE THREAD

**Issue by Dunedan** [steven-bruce-au/dynamodb-local-cloud-formation#1]
Thanks for putting up the code here, but it's essentially impossible to use it:
> If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.

(from https://choosealicense.com/no-license/)

Therefore please license your code so others can benefit from it as well.

**Comment by steven-bruce-au** [comment]
Added license
